services:
  postgres:
    image: postgres:16
    # network_mode: host
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: portfolio
    volumes:
      - ./.postgres-volume:/var/lib/postgresql/data
